### PR TITLE
Make compatible with Ruby 2.0

### PR DESCRIPTION
**Pull request by liger1978**
This pull request makes the gem compatible with Ruby 2.0 (the Ruby used in CentOS 7).  It doesn't break newer rubies.   I understand if you don't want to merge.  Just giving you the option!

### CODE REVIEW

**Comment by christopheraue** [comment]
Thanks!

**Comment by liger1978** [comment]
No problem and thanks! The gem now works great on CentOS 7 now and I've added it to my CentOS 7 yum repo here: https://harbottle.gitlab.io/ergel/7/x86_64/.

I don't know if you have any time, but I could do with some help using the gem for xrandr work.  I'm simply trying to:

1. Get all current outputs (connected and disconnected), including their current x and y position
2. Move outputs to new x and y positions

I'm trying to replace shelling-out to the xrandr command in an existing program.

I'm getting a bit confused between screens, crtcs and outputs. I understand if you don't have time and I'll probably work it out eventually!  Thanks!

**Comment by christopheraue** [comment]
If I remember correctly (it's been a while since I tinkered with it):
- Screen is the screen managed by X11. Every X11 session has only one these days.
- Outputs correspond to the connectors on your graphics card, i.e. your monitors.
- Crtcs correspond to the different output signals.

If you have two monitors connected and they display the exact same image (mirror mode) then there is only one distinct output signal: you have one screen, one crtc and two outputs for this one crtc. If each monitor shows its own individual image (like when your desktop spans across both monitors) there are two separate output signals: you still have one screen, but two crtcs with one output each.

There is a basic example regarding screens in the examples/ dir in this repo: https://github.com/christopheraue/ruby-xlib-objects/blob/20a4973cc7e32de6f6d1f1cf6c9f7f5a91ef12e3/examples/screen_events.rb. I'm not sure, this gem can be used to set screen dimensions, yet. You might need to get your hands dirty with the underlying Xlib API.

Hope, this helps.

**Comment by liger1978** [comment]
Ah OK, thanks!

**Pull request merged**
